### ISSUE TITLE
Add support for geo: links

### ISSUE THREAD

**Issue by happysat** [projecthorus/chasemapper#11]
Hello,

We did talk about it in IRC, a geo: link in prob. the telemetry table somewhere from the lat/lon position a hyperlink for Android based devices.
Ex. line 341 https://github.com/dl9rdz/rdz_ttgo_sonde/blob/master/RX_FSK/RX_FSK.ino.

Thanks, Regards Happysat

**Comment by darksidelemm** [comment]
The dialog box that pops up when you tap on a row in the telemetry table now include the current payload coords. Those coords are a geo: link, which you can tap on, and it will prompt to open a mapping app.

Hopefully this is sufficient! If not, re-open the issue and I can try something different.
