### ISSUE TITLE
Add OpenTopoMaps map layer

### ISSUE THREAD

**Issue by JRus-design** [projecthorus/chasemapper#16]
Hi Mark & company,
It´s possible to add one more layer map from OpenTopoMaps source?
https://wiki.openstreetmap.org/wiki/OpenTopoMap
I think it´s very useful to have a  topographic preview of the terrain when chasing a sonde!
Thanks & best regards
Javier (MD87IB on sondehub)

**Comment by darksidelemm** [comment]
I kind of added the ThunderForest maps ( https://github.com/projecthorus/chasemapper/blob/master/horusmapper.cfg.example#L77 ) for that purpose, but OpenTopoMap does look better, and no API key is required!

**Comment by darksidelemm** [comment]
Added in https://github.com/projecthorus/chasemapper/commit/a3e241c772cdd1002f0db99a2b6c26e2e8ce40b0
