### ISSUE TITLE
Unable to display auto_rx data

### ISSUE THREAD

**Issue by ElectronicallyE** [projecthorus/chasemapper#19]
No weather balloons locations are appearing on Chasemapper. I'm wanting to pull the data from auto_rx and I thought it'd work automatically because of the info in the wiki:
"ChaseMapper is configured to listen for these packets by default, so auto_rx and ChaseMapper should 'just work'."

In the auto_rx directory in station.cfg, I have the following variables set:
payload_summary_enabled = True
payload_summary_port = 55673

In the chase mapper directory in hoursmapper.cfg, I have set the following:
default_profile = 2
[profile_2]
profile_name = auto_rx
telemetry_source_type = horus_udp
telemetry_source_port = 55673
car_source_type = horus_udp (changed this, thinking it may show my vehicle location)
car_source_port = 55672

Also, my vehicle location isn't appearing. Are there conditions that must be met for this to appear (speed)? I don't have a GPSD, so is this even possible?

**Comment by darksidelemm** [comment]
Your profiles look OK. Make sure to confirm that the correct profile is selected in ChaseMapper.
A few questions:
- Is there actually any live data coming through? Chasemapper will only show live data, not historical data received by auto_rx.
- Are these running on the same RPI, or separate machines?
- You will need some kind of GPS receiver attached to the RPi for your car position to appear. You can either configure GPSD to talk to the GPS and have chasemapper talk to GPSD, or have chasemapper communicate with it directly (probably easier).

**Comment by ElectronicallyE** [comment]
Thanks for the quick reply.

Yep, the correct profile has been selected, being auto_rx.

When we are talking about auto_rx, is it only the data that my SDR receives, or does can it pull the data from Habhub? If it's the former, that's why I have mistaken it as not working.

Yep, they're running on the same Pi.

Okay, sure thing. Might as well ask, I've got a GY-GPS6MV2 with a u-blox NEO-6M module. Would that do the job?

**Comment by darksidelemm** [comment]
Yes, it's only data from your local receiver, not from Habhub. Turn on your test sonde and you should see the data appearing in chasemapper (once it has gps lock).

You may be able to interface that GPS receiver into your RPi, via the UART pins on the RPi header. Personally I use a USB GPS receiver, so I can put the antenna on the roof of the car.
