### ISSUE TITLE
Show most recent telemetry location from most recent balloon after restart

### ISSUE THREAD

**Issue by g7gpr** [projecthorus/chasemapper#25]
After a restart, the location of the most recent balloon is lost if there is no more telemetry received. It would be great if the most recent balloon's last known location, and last predicted landing point could appear on the map. Happy to implement this, probably by scanning the tail of the last log for the relevant information. Is there a smarter way?

**Comment by darksidelemm** [comment]
The behaviour you are experiencing is 100% the intended behaviour.

Chasemapper is intended to be started up near the start of the chase, and left running until the payloads are recovered. There was never any intention for it to reload old log files (in fact, logging of chase data was only added relatively recently).

I guess the question is - why are you restarting chasemapper in the middle of a balloon chase?

**Comment by g7gpr** [comment]
Never intentionally, usually a power supply problem. I don't want old telemetry cluttering up the map, as soon as a new chase starts, clean the slate. Sometimes covering the last few km happens on foot, and I lose supply when taking it out of the car.

**Comment by darksidelemm** [comment]
If you're leaving chasemapper on *continuously*, then there is a 'clear payload data' button to wipe old data.

It definitely sounds like you're using chasemapper in ways I didn't really intend it to be used. I intended it to be used in a car, with a good enough receive system to get a position pretty much down to the ground. If I have to go a long distance on foot I'd often bring DFing gear instead of a RPi.

For those last few km, if you don't want to bring a RPi, then maybe something like a TTGO would be more convenient...

**Comment by g7gpr** [comment]
In open ground definitely I can pick up data whilst the transmitter is on the ground. In the forest, not so easy unless I am very close.

Given that you intended chasemapper to be for car use, and my use case is on car and then on foot with an RPi in a backpack, I think this issue should probably be closed.

**Comment by darksidelemm** [comment]
Reading something in from a log file is not a *bad* idea, it's just that to do so will require a fair bit of coding to:
- Find the most recent log file.
- Read in said log file, and buffer up telemetry, or at least the last position.
The log file form is fairly simple, just lines of JSON, so it should be doable...

**Comment by g7gpr** [comment]
I'll fork and branch.

**Comment by darksidelemm** [comment]
So I would suggest:
- Create a new submodule in the chasemapper dir, maybe logread.py
- Add a configuration file option ('reload_last_position') as a boolean (True / False)
- Make a function which produces a list of log files in the log directory. As these are all timestamped, you should be able to sort these and pick the last one. 
- Make a function which reads in a file, and pumps the 'BALLOON TELEMETRY' data (skip the chase car and the prediction log entries) into handle_new_payload_position ( https://github.com/projecthorus/chasemapper/blob/055014c93c4a61444fc1b63bb26920a5fff38420/horusmapper.py#L185 ) 
- If the reload_last_position value is set, run this on startup.
