### ISSUE TITLE
Whitespace breaks config

### ISSUE THREAD

**Issue by Moll1989** [projecthorus/chasemapper#35]
Whitespace preceding a line in horusmapper.cfg prevents the line from being read correctly.

This arose for me by uncommenting the map path line for a docker install.  I accidentally left a whitespace before the line:
tile_server_path = /home/pi/Maps/

This resulted in no maps being accessible on the web interface.  

I understand that the solution to this could be that the user get the config syntax correct, but from a user experience perspective, I think it would be good if chasemapper ignored preceding whitespace in the config file.

**Comment by darksidelemm** [comment]
Interesting one... the config file is just parsed using Python's built in ConfigParser, so I'm not sure what options I have to fix it... 

Can you post an example of a working and broken config?

**Comment by Moll1989** [comment]
Here are the two config files (had to make them .txt for github to allow them).  

The only difference is the preceding space in one.  I have again, just now, confirmed that this prevents offline maps from being available.  The 'good' file works, and the 'leadingspace' file does not.

If it turns out that nothing can be easily done about this then perhaps a very clear warning could be issued in the comments at the top of the file??  Some users may take a long time to find the problem if they have this issue.

[horusmapper_good.txt](https://github.com/projecthorus/chasemapper/files/6564695/horusmapper_good.txt)
[horusmapper_leadingspace.txt](https://github.com/projecthorus/chasemapper/files/6564696/horusmapper_leadingspace.txt)

**Comment by darksidelemm** [comment]
OK I see the issue here - yes, putting a leading space in front of the variable name is going to break ConfigParser. I don't have a solution to this one. Every configuration file format is going to have similar formatting issues.

The best I can do here is remove the leading space in the example line that I say to comment out if running docker. Hopefully this will limit the opportunities for this to occur again.
