### ISSUE TITLE
gpsd speed is not what my car say

### ISSUE THREAD

**Issue by d0m1n1qu3** [projecthorus/chasemapper#39]
Hi,
i tried it out in my roadtrip, but chasemapper things i drive with something about 26000kph my car say i drive 80kph .. 

i have a second gps dongle an that works sometime with right values but my chasecar moving everytime with 0 - 16kps and its rotating .. also if i rest in bed ^^

what can i do to debug this to fix it?

best regards

**Comment by darksidelemm** [comment]
This sounds like issues to do with gps position glitches. 
As for the heading moving around while stationary - this is somewhat expected due to 'noise' in the GPS position.

**Comment by d0m1n1qu3** [comment]
so i digged into the code..
gpsd gives me something like this in TPV.speed ... 
```0.561
0.633
0.741
0.633
0.71
0.658
0.638
0.633
0.592
0.628
0.468
0.478
0.427
0.453
0.509
0.401
0.448
0.293
0.17
0.273
0
0
0
0
0
0
```
but in the GUI there is more like 238, 590, 1020 or something else ..

so i found out that the speed from gpsd is not used and is calculated by chasemapper ..

i added some logging lines
```Oct 25 21:11:12 chasemapper chasemapper[19607]: 2021-10-25 21:11:12,171 ERROR:Car Speed: 0.422
Oct 25 21:11:12 chasemapper chasemapper[19607]: 2021-10-25 21:11:12,174 ERROR:Car State Speed: 0.000
Oct 25 21:11:12 chasemapper chasemapper[19607]: 2021-10-25 21:11:12,177 ERROR:Car Speed: 0.170
Oct 25 21:11:12 chasemapper chasemapper[19607]: 2021-10-25 21:11:12,179 ERROR:Car State Speed: 308.724
Oct 25 21:11:13 chasemapper chasemapper[19607]: 2021-10-25 21:11:13,171 ERROR:Car Speed: 0.170
Oct 25 21:11:13 chasemapper chasemapper[19607]: 2021-10-25 21:11:13,173 ERROR:Car State Speed: 0.000
Oct 25 21:11:13 chasemapper chasemapper[19607]: 2021-10-25 21:11:13,176 ERROR:Car Speed: 0.154
Oct 25 21:11:13 chasemapper chasemapper[19607]: 2021-10-25 21:11:13,179 ERROR:Car State Speed: 224.398
Oct 25 21:11:14 chasemapper chasemapper[19607]: 2021-10-25 21:11:14,167 ERROR:Car Speed: 0.154
Oct 25 21:11:14 chasemapper chasemapper[19607]: 2021-10-25 21:11:14,169 ERROR:Car State Speed: 0.000
Oct 25 21:11:14 chasemapper chasemapper[19607]: 2021-10-25 21:11:14,172 ERROR:Car Speed: 0.247
Oct 25 21:11:14 chasemapper chasemapper[19607]: 2021-10-25 21:11:14,175 ERROR:Car State Speed: 126.686
Oct 25 21:11:15 chasemapper chasemapper[19607]: 2021-10-25 21:11:15,178 ERROR:Car Speed: 0.247
```

and here must be a bug i think .. because _speed is to high .. the car on the map is not moving, only spinning
```    car_track.add_telemetry(_car_position_update)

    _state = car_track.get_latest_state()
    _heading = _state["heading"]
    _heading_status = _state["heading_status"]
    _heading_valid = _state["heading_valid"]
    _speed = _state["speed"]


    logging.error("Car State Speed: %.3f" % (_speed))```

![grafik](https://user-images.githubusercontent.com/68078216/138756434-a3f106ce-c1e0-4c3f-a897-37cce7241ad6.png)

but i think i need help to understand the magic in 
`    def calculate_speed(self):
        """ Calculate Payload Speed in metres per second """
`

**Comment by darksidelemm** [comment]
The speed calculation code is just looking at distance change over time. The same kind of calculation is used to determine heading.
As a result, if your position is noisy (like it looks to be), your heading and speed will jump around. 

Could you try and connect your gps directly into chasemapper via serial and see if that works any better?

**Comment by d0m1n1qu3** [comment]
yes i can try it,

but why gives me gpsd 0.170 meters/s what is ok for the bad GPS indoor location, but the calculation in python think i drive with 308.724 meters/s ..
