### ISSUE TITLE
Variable defined twice in horusmapper.cfg

### ISSUE THREAD

**Issue by MikeTango** [projecthorus/chasemapper#49]
Hi, 

i can't get GPS to work and noticed that car_source_type seems to be defined twice, once in line 38 and then again in line 64. Is this intentional?

Chasemapper also ignores my request to find the USB GPS on /dev/ttyusb6 and tries calling /dev/TTYUSB0 all the time.

**Comment by darksidelemm** [comment]
The separate source type entries are for different profiles. There are use-cases where a different source for car position is used in different profiles.

Note that if you are using a serial GPS, then you need to define the serial port down here: https://github.com/projecthorus/chasemapper/blob/master/horusmapper.cfg.example#L89

The `car_source_port` entry is ` only used if horus_udp is selected, but still needs to be provided.` ( https://github.com/projecthorus/chasemapper/blob/master/horusmapper.cfg.example#L39C3-L39C103 )

**Comment by MikeTango** [comment]
Ah, didn't see the second profile. But you got me on another issue: The USB GPS is not mounting in /dev/ttyUSBwhatever. it shows up on lsusb as device 005.

**Comment by MikeTango** [comment]
Further investigation...GPS identified as ttyACM0. Works flawlessly now. Case can be closed.
