### ISSUE TITLE
chasemapper uploading sonde telemetry to sondehub

### ISSUE THREAD

**Issue by maciejopalinski** [projecthorus/chasemapper#57]
Is it possible to upload sonde telemetry alongside chase car telemetry to sondehub? I am using an external radio that sends HorusUDP packets to chasemapper and I need to upload them. Is it maybe possible for radiosonde_auto_rx to receive HorusUDP packets instead of connecting an SDR?

**Comment by darksidelemm** [comment]
Hi, apart from chase-car position, chasemapper does not upload balloon telemetry (amateur or radiosonde) to SondeHub. It was never intended to do that.

If you want to upload telemetry to SondeHub-Amateur, I would suggest implementing this in your receiver software using pysondehub - https://github.com/projecthorus/pysondehub/wiki/SondeHub-Amateur-Uploader-Class-Usage
