### ISSUE TITLE
Add habdec client support.

### ISSUE THREAD

**Issue by darksidelemm** [projecthorus/chasemapper#8]
Add support for connecting to a habdec (RTTY decoder written by @ogre - https://github.com/ogre/habdec ).
Example python Websockets client here: https://github.com/ogre/habdec/blob/master/code/pyClient/habdecClient.py  however it needs to be made Python 3.7 compatible.

**Comment by darksidelemm** [comment]
This one is on hold awaiting the ability to not need to poll for new data.

**Comment by michalfratczak** [comment]
This has been implemented.
Websocket server is asynchronous and push RTTY characters and sentences.
Python clients work for python 2 and 3.7
https://github.com/ogre/habdec/commit/fbbdff5d47bef61a2697d24c66af6caeec6db3e9

There is fresh bin release for windows and linux (PI and XU4 soon)
https://github.com/ogre/habdec/wiki

**Comment by darksidelemm** [comment]
Excellent, thanks! 
Hopefully I'll get around to implementing this in a few weeks. I may end up just writing a python shim to read from habdec's websocket and export payload summary messages, not sure yet.

**Comment by michalfratczak** [comment]
https://github.com/ogre/habdec/blob/master/code/pyClient/simple_listener.py
This ^ is a good starting point for a shim - dead simple.

**Comment by darksidelemm** [comment]
Given horusdemodlib now supports decoding of RTTY telemetry from most balloon payloads, I'm probably not going to bother with this now... I don't really have the time.
