### ISSUE TITLE
Pred Landing coordinates

### ISSUE THREAD

**Issue by fermars1974** [projecthorus/chasemapper#9]
Hello Mark,

Just a simple question, Where can I get the predicted landing coordinates easier? Digging in "~/chasemapper/log_files" I have found that those log files contains something called "pred_landing" with that info, and I think for now is the only way to get them. But, for instance, in Habhub you can put the mouse over the predicted landing icon and a pop up appears with that info. 
When you click on "Mark as recovered" you get the latest coordinates in flight. Just as an idea...would there be a chance to add a new button with the predicted landing coordinates somewhere?

Regards.
Fernando

**Comment by darksidelemm** [comment]
Should be easy enough to add it as a popup when you hover over the landing position. What will you be using them for? 

I would prefer to *not* to use the prediction coordinates for mark-as-recovered, as often if you are still receiving after landing the predictor can get confused and start predicting the sonde as if it were ascending very slowly, resulting in a prediction a long way asay.

**Comment by fermars1974** [comment]
Well, there are several reasons we are interested in this feature. First, If you are chasing your own sonde and you find a radio telemetry error (I mean, your RS41 fails and your backup as well!!), having this coordinates is better than nothing to try to recover it on site. Second, I copy/paste them on Google Earth or Maps to pan around that place and know it better while getting closer (or later) and third I like to compare the exact coordinates where you find the sonde and predicted ones for future references.
I know now that you can find them in the log file, but it would be easier and quicker to have a button that show them and let you copy them. A pop up would be great too.

I agree about not to use the mark-as-recovered button to get the predicted coordinates, It was just an example of what I am trying to explain, a button to pop-up a window where you can find them.
Of course, is just something I miss I do not pretend giving you a headache with it :-).

**Comment by darksidelemm** [comment]
If you click on the landing marker, the lat/lon for that marker position will be copied to your clipboard. I've only done this for the main prediction marker, not the abort prediction marker.
